spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reserve?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hidden-method:
      filter:
        enabled: true
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 592732293@qq.com #发送邮件的邮箱地址
    password: gmbwcjsgunvdbegc #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
server:
  port: 8081
mybatis:
  type-aliases-package: com.reserve.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
